### ISSUE TITLE
How do I get CN signature?

### ISSUE THREAD

**Issue by pyuna** [AlexandrovLab/SigProfilerAssignment#102]
Is there a way to get CN signature results like SBS?

**Comment by mdbarnesUCSD** [comment]
Hi @pyuna,

Thank you for reaching out! To better help, we need some additional information about the issue you're facing. Could you please provide:

- The specific version of the software or package you're currently using?
- The command or process you attempted
- Any output, logs, or error messages that you received as a result of running the command.

**Comment by pyuna** [comment]
Thank you for your answer.
You are using version 0.0.32 of SigProfiler Assignment. There is no error or anything. I changed context_type and checked SBS, DBS, and ID. But I don't know how to check CN.

from SigProfilerAssignment import Analyzer as Analyze
Analyze.cosmic_fit(samples, output, input_type="matrix", **context_type**="96",
                   collapse_to_SBS96=True, cosmic_version=3.3, exome=False,
                   genome_build="GRCh37", signature_database=None,
                   exclude_signature_subgroups=None, export_probabilities=False,
                   export_probabilities_per_mutation=False, make_plots=False,
                   sample_reconstruction_plots=False, verbose=False)

**Comment by mdbarnesUCSD** [comment]
The input needs to be a CN matrix created from SigProfilerMatrixGenerator. Could you please confirm that you are using a CN input matrix and not a SBS, DBS, or ID matrix?

**Comment by pyuna** [comment]
Checked it. CN matrix is not used.
If I use CNmatrix, what should I choose for context_type?

**Comment by mdbarnesUCSD** [comment]
The context_type should be set to "48".

**Comment by mdbarnesUCSD** [comment]
Please reach out if you have any additional issues.
