### ISSUE TITLE
Question regarding exclude_signature_subgroups option

### ISSUE THREAD

**Issue by sigven** [AlexandrovLab/SigProfilerAssignment#103]
Hi,

Thanks for a very useful tool:) I had a question regarding optimized tumortype-specific re-fitting, using the `exclude_signature_subgroups` option. 

From what I can see from the COSMIC overview of SBS signatures, some tumor types are associated, yet frequently to a minor extent, _partly_ with the signature subgroups you have outlined (MMR, Treatment, BER etc). This can be seen from the tissue distribution. Considering this observation, it is frequently challenging to establish the subset of signatures that I want to use for re-fitting of variants coming from a particular tumor type. So my question is kind of two-fold:

- Do you have a recommended setting (with respect to the `exclude_signature_subgroups` option) for optimal re-fitting of signatures given sample input data from the major tumor types (i.e. Breast, Lung, Pancreas, Colon/Rectum, CNS/Brain, Liver, Skin, Overy, Lymphoid, Myeloid, Head/Neck, Kidney etc.)?, _OR_ 
- Would it be possible to allow the user to rather feed in a selected set of signatures (e.g. `SBS1,SBS3,SBS5 .. SBS17`) for which re-fitting is to be performed (rather than giving groups of pre-selected signatures for exclusion)?

Happy to hear your thoughts regarding this,

kind regards,
Sigve

**Comment by marcos-diazg** [comment]
Dear @sigven,

Thanks so much for your questions. Indeed, both ideas you mentioned could be helpful, and we will definitely keep them in mind for future development.

Regarding the set of signatures to include/exclude per cancer type, the most challenging part would be defining those sets, especially given that COSMIC v3.4 reference signatures were extracted from multiple independent cohorts.

At the moment, our recommendation is for the users to make their own decisions regarding which set of signatures to include or exclude (and justify it accordingly). In this regard, it is possible to use the `signature_database` parameter to include the set of signatures of your choice. An easy way to do this is by downloading the reference COSMIC signatures from https://cancer.sanger.ac.uk/signatures/downloads/, and then removing the signatures that you want to exclude from your analysis by directly removing the corresponding columns from the signature matrix.

Again, I think your suggestion of providing a parameter for users to do this directly could be helpful (similar to the current `exclude_signature_subgroups` parameter), and we'll try to explore it in the future.

Thanks again! Best,

Marcos

**Comment by sigven** [comment]
Dear @marcos-diazg,

Thanks a lot for your swift response! And I totally agree with your comment, it is challenging to establish some recommendations on signatures to include per tumor type, this is indeed not straightforward, and strategies chosen may also depends on the overall purpose of the fitting procedure. I did not think of feeding in a modified COSMIC signature matrix, thanks for that tip, makes sense! 

thanks for your help,

best,
Sigve
