### ISSUE TITLE
Possible to provide path to existing reference genome data?

### ISSUE THREAD

**Issue by sigven** [AlexandrovLab/SigProfilerAssignment#105]
Hi,

For some reason I am unable to install the reference genome (the command is hanging,not finishing), using
`from SigProfilerMatrixGenerator import install as genInstall`
`genInstall.install('GRCh37')`

It is also unclear where the tool downloads this (potentially quite big) dataset? It would be very helpful with some log output that explains what is happening, and whether the download is in progress or not. Moreover, it would be even more handy to provide a path to an existing reference file to the different commands as an argument (i.e. `--refgenome`), considering that many bioinformatics users have these files already downloaded on their computer. Do you think this would be possible at all?

best,
Sigve

**Comment by mdbarnesUCSD** [comment]
Hi @sigven,

You can find more information about reference genome installation at the [GitHub for SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator). Please post there if you encounter issues during installation. If you are downloading from behind a firewall, you can us rsync. There is a parameter 'volume' for specifying a destination to save and load the tsb files from. Hope this helps!

**Comment by sigven** [comment]
Hi @mdbarnesUCSD,
Thanks for helpful response:) Download of reference genomes works fine. But I am still struggling to see whether I can feed e.g. the `cosmic_fit` routine with the path to the downloaded reference genome (if I have this in a custom folder)? I believe the same goes for the `https://github.com/AlexandrovLab/SigProfilerAssignment/tree/main/SigProfilerAssignment/data/Reference_Signatures` folder with COSMIC reference signatures, how does the `cosmic_fit` function know/determine in which folder these data are located?

best,
Sigve

**Comment by mdbarnesUCSD** [comment]
We have added support for the "volume" parameter across SigProfilerMatrixGenerator, SigProfilerPlotting, and SigProfilerAssignment. This variable specifies where to save and load reference genomes, plot templates, and pre-plotted COSMIC signatures. Alternatively, you can specify the environmental variable for each of the tools as such:

- SIGPROFILERMATRIXGENERATOR_VOLUME
- SIGPROFILERPLOTTING_VOLUME
- SIGPROFILERASSIGNMENT_VOLUME

**Comment by sigven** [comment]
Wow, this is really nice! Will check it out shortly.

Thanks,
Sigve
