### ISSUE TITLE
Connection timed out while downloading the ref genome to install.

### ISSUE THREAD

**Issue by AngelGarciaDeLaTorreGarcia** [AlexandrovLab/SigProfilerAssignment#107]
Hello!!

I am trying to install the reference genome with this line `genInstall.install('GRCh38', rsync=False, bash=True)` but the website seems to be down. Can you check if the website is really down or it is just me? If its the first case, how can I get the Ref Genome?

Regards,

Ángel

**Comment by mdbarnesUCSD** [comment]
Hi @AngelGarciaDeLaTorreGarcia,

Are you downloading from behind a firewall? SigProfilerMatrixGenerator has a [status badge for the FTP server](https://stats.uptimerobot.com/jjqW4Ulymx).

Thanks!

**Comment by AngelGarciaDeLaTorreGarcia** [comment]
Hello,

Just deactivated firewall and tried again, but still it does not work, same failure.

**Comment by mdbarnesUCSD** [comment]
Hi @AngelGarciaDeLaTorreGarcia,

Please update SigProfilerMatrixGenerator and try to download the reference genome again. If you encounter any issues with installing reference genomes, please reach out at [SigProfilerMatrixGenerator's repository](https://github.com/alexandrovlab/SigProfilerMatrixGenerator).

Thanks!
