### ISSUE TITLE
Signature decomposition error -  negative values

### ISSUE THREAD

**Issue by maia-munteanu** [AlexandrovLab/SigProfilerAssignment#109]
Hi there!

I've been having this recurring issue when I try to decompose a set of signatures and assign weights to my samples. 
For example, I try to decompose 5 samples into 13 signatures but get this error, always at sample 2. 

                                         

```                                            
 ################ Sample 2 #################
on 2: ############################# Initial Composition ####################################
on 2:    SBS1  SBS2  SBS5  SBS10a  SBS22a  SBS28  SBS31  SBS36  SBS52  SBS84  SBS85  SBS93  SBS97  SBS96B  SBS96C  SBS96D  SBS96E  SBS96I  SBS96L
      0   0.0   0.0   0.0     0.0     1.0    0.0    0.0    1.0    0.0    1.0   -1.0    0.0    0.0     0.0     0.0     0.0     0.0     0.0     1.0
on 2: L2%:  0.9637371811469586
|████████████████⚠︎                       | (!) 2/5 [40%] in 0.2s (279.38/s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmunteanu/.conda/envs/SigProfilerAssignment/lib/python3.9/site-packages/SigProfilerAssignment/Analyzer.py", line 4, in decompose_fit
    decomp.spa_analyze(samples=samples,  output=output, signatures=signatures, signature_database=signature_database,nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty,genome_build=genome_build, cosmic_version=cosmic_version, make_plots=make_plots, collapse_to_SBS96=collapse_to_SBS96,connected_sigs=connected_sigs, verbose=verbose,decompose_fit_option= True,denovo_refit_option=False,cosmic_fit_option=False,devopts=devopts,new_signature_thresh_hold=new_signature_thresh_hold,exclude_signature_subgroups=exclude_signature_subgroups,exome=exome,input_type=input_type,context_type=context_type,export_probabilities=export_probabilities, export_probabilities_per_mutation=export_probabilities_per_mutation)
  File "/home/mmunteanu/.conda/envs/SigProfilerAssignment/lib/python3.9/site-packages/SigProfilerAssignment/decomposition.py", line 538, in spa_analyze
    result = sub.make_final_solution(processAvg, genomes, allsigids, layer_directory2, mutation_type, index, colnames,
  File "/home/mmunteanu/.conda/envs/SigProfilerAssignment/lib/python3.9/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 566, in make_final_solution
    exposureAvg[:,r],L2dist,cosine_sim = ss.remove_all_single_signatures(processAvg, exposureAvg[:, r], allgenomes[:,r], metric="l2", \
  File "/home/mmunteanu/.conda/envs/SigProfilerAssignment/lib/python3.9/site-packages/SigProfilerAssignment/single_sample.py", line 607, in remove_all_single_signatures
    return H, successList[2], cos_sim(genomes, np.dot(W,H)) #first value is the exprosure, second value is the similarity (based on the similarity matic), third value is the cosine similarity
ValueError: shapes (96,19) and (18,) not aligned: 19 (dim 1) != 18 (dim 0)
```

The issue seems to come from a negative value that appears in the initial compositions, here due to SBS85. On the other side, if I run the solution with 14 signatures, the decomposition works perfectly fine and doesn't throw any errors. As far as I can tell, there is nothing wrong with my mutation or signature matrices - these were also generated with SigProfilerMatrixGenerator and Extractor. I'm also using the latest version of SigProfilerAssignment, but this error appears in previous versions too. 

The metadata for the decomposition:

```
-------Python and Package Versions-------
Python Version: 3.9.15
SigProfilerPlotting Version: 1.3.18
SigProfilerMatrixGenerator Version: 1.2.17
SigProfilerAssignment Version: 0.1.0
Pandas version: 1.5.3
Numpy version: 1.25.2

--------------EXECUTION PARAMETERS--------------
INPUT DATA
	input_type: matrix
	output: ./Test
	samples: Test.txt
	reference_genome: GRCh37
	context_types: 96
	exome: False
COSMIC MATCH
	cosmic_version: 3.4
	nnls_add_penalty: 0.05
	nnls_remove_penalty: 0.01
	initial_remove_penalty: 0.05
	de_novo_fit_penalty: 0.02
	export_probabilities: True
	collapse_to_SBS96: True
	denovo_refit_option: False
	decompose_fit_option: True
	cosmic_fit_option: False

-------Analysis Progress-------
[2024-01-24 11:42:48] Analysis started:

 Decomposing De Novo Signatures  .....
 [2024-01-24 11:42:48] Assigning decomposed signature

```
I have attached the 96 mutation matrix and the 13 and 14 signature sets below, perhaps you can reproduce this error. 

[SBS96_S14_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/14037089/SBS96_S14_Signatures.txt)
[SBS96_S13_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/14037091/SBS96_S13_Signatures.txt)
[Test.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/14037092/Test.txt)

**Comment by marcos-diazg** [comment]
Hi Maia,

I hope you are doing well, and thanks so much for your interest in our tool! Thanks for pointing this numerical error out. We are currently working on an update to fix it, which will be included in the next release of SigProfilerAssignment.

However, I would like to point out a potential issue with your analysis, and this is in regard to the total number of mutations in your samples. Independently of the numerical issue reported, any signature analysis performed with samples with 2 or 3 total mutations will be highly inaccurate, due to the nature of the mathematical reconstruction performed, and the fact that you are using the SBS-96 classification, with a much larger number of features than actual mutations. I strongly suggest checking the similarity of the reconstructed samples (which you can find in the `Solution_Stats` folder), and filter out any cases with low cosine similarities (e.g., you can use 0.9 as a first quality threshold).

Happy to continue the analysis conversation over email (mdiazgay@ucsd.edu), and thanks again for your feedback on the tool!

Best wishes,

Marcos

**Comment by maia-munteanu** [comment]
Hi Marcos,

Thanks a lot for getting back to me! Will keep an eye out for the new release. 
Regarding your comment about the potential inaccuracy of decomposing samples with very few mutations, thanks for pointing it out, will make sure to take the cosine similarities into account. In my current analysis, I am more often than not interested in the decomposition of the de novo signature spectra into COSMIC rather than the sample fitting, but I couldn't find a way to decouple the decomposition and fitting steps with the SigProfilerAssignment tool. Is there a way currently to just decompose the spectra and not perform fitting with the COSMIC signatures in all the samples?


Many thanks,
Maia

**Comment by marcos-diazg** [comment]
Hi again Maia,

Currently, there is no separate module for decomposition and refitting in SigProfilerAssignment. It would be something to keep in mind for future updates. Thanks for the feedback! Alternatively, if you are just interested in the decomposition of _de novo_ signatures, I suggest performing the analysis with just one or a few samples in your input mutational matrix, to speed up the process.

I hope this helps. Best,

Marcos

**Comment by maia-munteanu** [comment]
Hi Marcos,

No worries, thank you for letting me know! Will take your suggestion and run with fewer samples.


Many thanks,
Maia
