### ISSUE TITLE
Python Version Issue

### ISSUE THREAD

**Issue by hpoisner** [AlexandrovLab/SigProfilerAssignment#111]
Hi I think this is a Python version issue but I get the following error when I run this command

Analyze.cosmic_fit(samples="path/to/vcfs",
                  output='signatures',
                  input_type='vcf',
                  context_type='96',
                  genome_build='GRCh38',
                  cosmic_version=3.3)

AttributeError: 'DataFrame' object has no attribute 'append'
Specifically related to this line
-> 2924     trans = trans.append(a)

Python Version I use
Python 3.10.12 | packaged by conda-forge

**Comment by hpoisner** [comment]
Sorry I think this is a Pandas issue not a Python issue.

**Comment by marcus-r-kelly** [comment]
I know this is closed, but I've run into the same thing and it's worth posting a fix.

The "append" method was deprecated in later versions of `pandas`, so there is a python version ceiling on this suite. In general, you should create your own environment for sigprofiler as it will prevent you from working with up-to-date versions of other modules.
