### ISSUE TITLE
Error: "The context-96 decomposition plots pages were not able to be generated."

### ISSUE THREAD

**Issue by thebrownlife** [AlexandrovLab/SigProfilerAssignment#116]
Hi, 
I am using SigProfilerMatrixGenerator and SigProfilerExtractor tools to identify mutational signatures in my tumour samples. Everything runs smoothly until the decomposition results need to be plotted. At the end of the job, the following is printed.

"
There is no signature over the thresh-hold stability. We are selecting the lowest possible number of signatures.

 Denovo Fitting .....
|████████████████████████████████████████| 88/88 [100%] in 3.8s (23.25/s)

 Decomposing De Novo Signatures  .....
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.
The context-96 decomposition plots pages were not able to be generated.

 Assigning decomposed signature
|████████████████████████████████████████| 88/88 [100%] in 3.4s (25.90/s)

Your Job Is Successfully Completed! Thank You For Using SigProfilerExtractor.
"

Even though the following files are generated, 

1. De_Novo_map_to_COSMIC_SBS96.csv
2. Cosmic_SBS96_Decomposition_Log.txt
3. COSMIC_SBS96_Signature_Assignment_log.txt

the decomposition plots are not. I can tell that each sample was assigned a mixture of COSMIC from the files above. But I am really confused why they're not being plotted. No explanation or further steps are outlined for me to solve it. Can someone please help? Thanks a lot.

**Comment by mdbarnesUCSD** [comment]
Hi @thebrownlife,

Could you please provide the version of tools as well as your JOB_METADATA.txt file in the output directory? It would be great to know the number of samples that you are using as well.

Thanks!

**Comment by thebrownlife** [comment]
Hi @mdbarnesUCSD ,'

Thanks a lot for your prompt reply.

The metadata txt file below shows the versions of all the tools. I have 88 samples collected from whole-exome sequencing of tumour DNA. 


```
THIS FILE CONTAINS THE METADATA ABOUT SYSTEM AND RUNTIME


-------System Info-------
Operating System Name: Linux
Nodename: wd1
Release: 5.4.0-146-generic
Version: #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023

-------Python and Package Versions------- 
Python Version: 3.7.10
SigProfilerExtractor Version: 1.1.15
SigProfilerPlotting Version: 1.3.2
SigProfilerMatrixGenerator Version: 1.2.13
SigProfilerAssignment Version: 0.0.19
Pandas version: 1.3.5
Numpy version: 1.21.6
Scipy version: 1.7.3
Scikit-learn version: 1.0.2

--------------EXECUTION PARAMETERS--------------
INPUT DATA
	input_type: matrix
	output: Extractor_k3
	input_data: /disk3/users/anisha/WES/SigProfiler_HK_all/output/SBS/HKAll.SBS96.exome
	reference_genome: GRCh38
	context_types: SBS96
	exome: True
NMF REPLICATES
	minimum_signatures: 3
	maximum_signatures: 3
	NMF_replicates: 100
NMF ENGINE
	NMF_init: random
	precision: single
	matrix_normalization: gmm
	resample: True
	seeds: random
	min_NMF_iterations: 10,000
	max_NMF_iterations: 1,000,000
	NMF_test_conv: 10,000
	NMF_tolerance: 1e-15
CLUSTERING
	clustering_distance: cosine
EXECUTION
	cpu: 80; Maximum number of CPU is 80
	gpu: False
Solution Estimation
	stability: 0.8
	min_stability: 0.2
	combined_stability: 1.0
	allow_stability_drop: False
COSMIC MATCH
	opportunity_genome: GRCh38
	cosmic_version: 3.3
	nnls_add_penalty: 0.05
	nnls_remove_penalty: 0.01
	initial_remove_penalty: 0.05
	export_probabilities: True
	collapse_to_SBS96: True

-------Analysis Progress------- 
[2024-02-21 16:35:54] Analysis started: 

##################################

[2024-02-21 16:35:54] Analysis started for SBS96. Matrix size [96 rows x 88 columns]

[2024-02-21 16:35:54] Normalization GMM with cutoff value set at 9600

[2024-02-21 16:36:41] SBS96 de novo extraction completed for a total of 3 signatures! 
Execution time:0:00:47

[2024-02-21 16:37:09] Analysis ended: 

-------Job Status------- 
Analysis of mutational signatures completed successfully! 
Total execution time: 0:01:15 
Results can be found in:  Extractor_k3  folder
```

**Comment by mdbarnesUCSD** [comment]
Thanks for sending that over, could you please start by updating the SigProfiler packages to their current versions?

sigProfilerPlotting 1.3.20
SigProfilerMatrixGenerator 1.2.25
SigProfilerAssignment 0.1.3
SigProfilerExtractor 1.1.23

**Comment by thebrownlife** [comment]
hi @mdbarnesUCSD,

Updating to the latest packages did the trick. Thanks for pointing that out :)
