### ISSUE TITLE
Tracking SBS probability for individual mutation?

### ISSUE THREAD

**Issue by Kdreval** [AlexandrovLab/SigProfilerAssignment#118]
Hi team!
Thank you for this amazing tool!
I am interested in tracking the probability of individual mutation being assigned for a particular signature when the maf file is supplied as input. I was expecting that this is what `export_probabilities_per_mutation` argument is for, but it just outputs a matrix without direct linkage to the original mutation.
I envision a functionality to append columns to the original maf file, where the new columns represent the SBS and the values are probabilities of the particular signature, but cannot find whether this is tracked or not.

Can you please suggest whether there is a build-in option to do so?

Thanks again!

**Comment by mdbarnesUCSD** [comment]
Hi @Kdreval,

Please make set both export_probabilities_per_mutation and export_probabilities to True. After doing so, there should be a directory created called `Decomposed_Mutation_Probabilities` and inside there will be a file for each sample.

Please let me know if this resolves your issue, thanks!

**Comment by Kdreval** [comment]
Hi @mdbarnesUCSD ,
Thank you for your help - this folder contains the files exactly as I had in mind.
Will close this issue!
