### ISSUE TITLE
UnboundLocalError: cannot access local variable 'samples' where it is not associated with a value

### ISSUE THREAD

**Issue by merlevede** [AlexandrovLab/SigProfilerAssignment#121]
Hello,

I try to use SigProfilerAssignment on ~70 samples but I am stuck with an error.
I call the function Analyze.cosmic_fit this way:
```
Analyze.cosmic_fit(samples="../outputs/mutational_signatures/filtered_variant_lists/", output="../outputs/mutational_signatures/SigProfilerAssignment/", input_type="vcf", context_type="96",
                   collapse_to_SBS96=True, cosmic_version=3.4, exome=True,
                   genome_build="GRCh38", exclude_signature_subgroups=None, 
                   export_probabilities=False, export_probabilities_per_mutation=False, 
                   sample_reconstruction_plots="png", make_plots=True, verbose=False)

```
The filtered_variant_lists folder contains simple text files (with no extension) formatted like this:

```
1	11027582	C-1973-FIXT-01	T	C
1	23088913	C-1973-FIXT-01	G	T
1	235720824	C-1973-FIXT-01	T	A
2	20447600	C-1973-FIXT-01	C	CA
2	26429712	C-1973-FIXT-01	G	A
2	27085274	C-1973-FIXT-01	G	A
2	42048636	C-1973-FIXT-01	CAGGCTACACCA	C
2	62000820	C-1973-FIXT-01	C	A
2	73452762	C-1973-FIXT-01	GAACTA	G
```

I get the following error: 

> UnboundLocalError: cannot access local variable 'samples' where it is not associated with a value

I am using a conda env with in particular:

> pandas                    1.5.3
> sigprofilerassignment     0.1.0
> sigprofilermatrixgenerator 1.2.22
> sigprofilerplotting       1.3.18

Do you have any idea what could be the issue here?

Thanks in advance,
Jane

**Comment by mdbarnesUCSD** [comment]
Hi @merlevede,

If you change the extension of your input files to .vcf, does this fix the issue? Please let us know.

Thanks!

**Comment by merlevede** [comment]
> Hi @merlevede,
> 
> If you change the extension of your input files to .vcf, does this fix the issue? Please let us know.
> 
> Thanks!

Indeed, adding the suffix .vcf solved this issue. Thanks for your answer!
