### ISSUE TITLE
SBS signatures with numbers above 96

### ISSUE THREAD

**Issue by jasmussen-bcm** [AlexandrovLab/SigProfilerAssignment#122]
I recently ran SigProfiler on some TCGA data and got samples enriched for SBS signatures with values like "SBS288", "SBS384", "SBS1536", "SBS4608", and "SBS6144." What signatures are these referring to? I don't see any on the COSMIC website.
https://cancer.sanger.ac.uk/signatures/sbs/

**Comment by mdbarnesUCSD** [comment]
The COSMIC signatures as of v3.4 release are supported for contexts SBS96, ID83, DBS78, SV32, CNV48, and RNA-SBS192. The contexts that you see for SBS288, SBS384, SBS1536, SBS4608, and SBS6144 are extended contexts that can be useful for analysis, but are not supported contexts for COSMIC signatures. The parameter collapse_to_SBS96 can be used to collapse from a higher context (ie SBS1536) down to SBS96, which is the context that SBS COSMIC signatures are currently presented in.

**Comment by jasmussen-bcm** [comment]
Thank you! 

And, how do I interpret the "Assignment_Solution_Activities.txt" file with the signatures by sample ID? The values in the matrix don't appear to be scaled. Are these the count of each mutation associated with each signature per sample?

**Comment by mdbarnesUCSD** [comment]
Please reach out if you have any additional questions.
