### ISSUE TITLE
How to generate DBS and ID report?

### ISSUE THREAD

**Issue by alexgby** [AlexandrovLab/SigProfilerAssignment#126]
Hi,

I've looked in the documents, doc, publication. But I can't find the input parameter to set SigProfilerAssignment to generate DBS and ID solutions. The publication mentioned the DBS and ID few times. But I can't find any description in the README. 

Thank you.

**Comment by mdbarnesUCSD** [comment]
Hi @alexgby,

You will want to use the parameter `context_type` and set it to "DINUC" for DBS and "ID" for Indels.

Please reach out if you have any additional questions.
