### ISSUE TITLE
incompatibility with conda when importing pyPDF2

### ISSUE THREAD

**Issue by FelixMoelder** [AlexandrovLab/SigProfilerAssignment#128]
First of all thanks for developing this tool.

While using it I stumbled about an incompatibility when installing the package via bioconda as SigProfilerAssignment requires pyPDF2.
pyPDF seems to have a complicated version history causing this issue.
The requirement for this tool is `pyPDF2 >=3.0` being available at [PyPI](https://pypi.org/project/PyPDF2/).
As the PyPI pages tells the pyPDF project decided to release versions >=3.1 as a separate package being just called `pypdf` (https://pypi.org/project/pypdf/).
The difference between both package is that the first one is imported via `import PyPDF2` and the newer one via `import pypdf`.
On conda there is no differentiation between `pypdf` and `pypdf2` letting SigProfilerAssignment fail when importing `pypdf2`.
To increase compatibility it would be helpful if `pypdf2` could be replaced by `pypdf`.

**Comment by mdbarnesUCSD** [comment]
Thanks @FelixMoelder for the discussion of this issue. We will be merging this pull request.
