### ISSUE TITLE
SigProfilerAssignment for targeted panels?

### ISSUE THREAD

**Issue by MiPSch** [AlexandrovLab/SigProfilerAssignment#130]
Does SigProfilerAssignment work for targeted panels such as TSO500 and FMI CDx? I guess not?

If it works, is there anything special to keep in mind when applying SigProfilerAssignment to targeted Panels?

**Comment by marcos-diazg** [comment]
Dear @MiPSch,

Thanks so much for your interest in SigProfilerAssignment! Also, thanks for bringing up a critical question regarding the application of our tool, as well as the assignment of mutational signatures in general. As it has been described in different literature reviews (e.g., nicely exemplified in Box 1 in [Koh _et al_. 2021](https://www.nature.com/articles/s41568-021-00377-7)), the power to accurately assign signatures to individual tumors is drastically reduced in WES and targeted panels compared to WGS. This is a consequence of the significant decrease in the total number of mutations captured by these targeted approaches, which do not consider mutations in the whole genome.

Considering this, our common recommendation is to use signature analysis in cancer types that accumulate large numbers of mutations and/or only to detect/assign signatures that are commonly related to the accumulation of large numbers of mutations, for example, highly mutagenic environmental exposures (tobacco smoking - SBS4, or UV light - SBS7a/b/c/d) and DNA repair deficiencies (MSI - SBS6/14/15/20/21/26/44, or POLE mutations - SBS10a/b/28). Although computationally, the tool only requires an input mutational matrix, and therefore, it will work for any input data provided, the recommendation is to check the reconstruction accuracy to assess the reliability of the results given your input set of mutations.

Happy to discuss more and resolve any additional doubts about this analysis over email (mdiazgay@ucsd.edu). Thanks again for your interest!

Best wishes,

Marcos
