### ISSUE TITLE
mouse mutational signatures

### ISSUE THREAD

**Issue by MariaCartolano** [AlexandrovLab/SigProfilerAssignment#133]
Hello,

I would need a short information. Are the reference signatures assigned to mice fully generated in silico based on mouse mutational opportunities?

Cheers
Maria

**Comment by marcos-diazg** [comment]
Hi Maria,

I hope you are doing well, and thanks so much for your continuous interest in our tools! I think we discussed this topic in a previous email conversation a few months ago, but our reference signatures for mm9 and mm10 mouse genomes (available in the recently reformatted COSMIC Mutational Signature website [here](https://cancer.sanger.ac.uk/signatures/downloads/)) were actually derived in silico based on the different trinucleotide/dinucleotide frequencies for the different genomes (which can be found as part of the SigProfilerMatrixGenerator [here](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/tree/master/SigProfilerMatrixGenerator/references/chromosomes/context_distributions)), with the GRCh37 signatures being the reference signatures.

Just in case, I would like to reiterate that there is a caveat with this approach, as it is worth noting that these are still human signatures lifted to other species. This means that some signatures related to certain biological processes exclusive from humans could actually not be meaningful for other species. More information can be found in this previous issue: https://github.com/AlexandrovLab/SigProfilerExtractor/issues/91#issuecomment-917743226.

I hope this helps, and please feel free to reach out by email or reopening this issue if you have additional questions.

Best wishes,

Marcos
