### ISSUE TITLE
Unclear Scope

### ISSUE THREAD

**Issue by DarioS** [AlexandrovLab/SigProfilerAssignment#134]
README file doesn't explain difference to SigProfilerSingleSample. Also, it seems SigProfilerAssignment can't do structural variants.

**Comment by mdbarnesUCSD** [comment]
Hi @DarioS,

SigProfilerAssignment does support structural variants through matrix inputs but you are correct. If you do not have a matrix though, then as of [SigProfilerAssingment v0.1.7](https://github.com/AlexandrovLab/SigProfilerAssignment/releases/tag/v0.1.7) you will need bedpe files that adhere to this format specified in [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator#structural-variant-matrix-generation).

We will look to add support for this in the next release.

**Comment by DarioS** [comment]
I don't think it can work with any kind of input. There seems to be no suitable value of `context_type` that a user could specify.

> `context_type`: String. Valid options include "96", "288", "1536", "DINUC", and "ID".

In addition, the web server version has no radio button option for S.V.

![image](https://github.com/AlexandrovLab/SigProfilerAssignment/assets/631218/d06cf3f4-580a-4d7e-ad3c-aebe8ff0bdbd)

Finally, there is no mention of structural variant support in README file.

**Comment by mdbarnesUCSD** [comment]
The context_type parameter is not relevant for matrix input. The most current version of code is what is hosted in this repository. We will expand the documentation on the README to help make things more clear.

**Comment by rvangara** [comment]
Hi @DarioS,

To answer your question regarding SigProfilerSingleSample: it is an older version of the assignment tool and is no longer under development. We might archive it soon. All further developments will be done on the SPA tool.

**Comment by DarioS** [comment]
I shall focus on using SigProfilerAssignment.
