### ISSUE TITLE
file used to plot following plot

### ISSUE THREAD

**Issue by wangzunq** [AlexandrovLab/SigProfilerAssignment#142]
![image](https://github.com/user-attachments/assets/fc9e0d55-7fa2-4227-8a36-19af77ffa298)
I would like to subset the file into assigned SBS84 and SBS5 samples seperately to replot across all samples. Which file should I use? The columns I need are samples, reference allele and tumor allele and total alt count. Thank you for any help

**Comment by mdbarnesUCSD** [comment]
Hi @wangzunq,

In the COSMIC solution directory there will be a text file for the activities matrix. This file contains information for each sample and the number of mutations from each signature that were assigned to it.

Are you interested in generating the probability matrix per mutational context for each sample? If you are that requires VCF input files and that `export_probabilities_per_mutation` be set to True. 

Please reach out if you have any additional questions.
