### ISSUE TITLE
some question about exome=true

### ISSUE THREAD

**Issue by shenhaizhongdechanrao** [AlexandrovLab/SigProfilerAssignment#143]
Hello, can I directly use your exome reference signature with other software for feature extraction? I would like to compare the performance between the software. I would like to know if, when using exome=True, any other operations are performed on the input data besides sampling according to the V7 bed, such as normalization.The path is "SigProfilerAssignment/data/Reference_Signatures/GRCh38/COSMIC_v3.4_SBS_GRCh38_exome.txt"

**Comment by marcos-diazg** [comment]
Dear @shenhaizhongdechanrao,

Thanks so much for your interest! Of course, feel free to use our renormalized version of the COSMIC reference signatures based on the exome trinucleotide context. Indeed, please let us know if we can help with anything. You can reach out by email at mdiazgay@health.ucsd.edu.

Regarding your question, you were totally correct. When using `exome=True`, the input data is downsampled to the exome, according to the BED file provided in [SigProfilerMatrixGenerator](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator) and the renormalized version of the signatures is used. SigProfilerAssignment does not perform any normalization of the input data, as we decided to directly renormalize the reference signatures instead.

I hope this makes sense, and please reopen the ticket or send us an email if you have any further questions.
