### ISSUE TITLE
 Insufficient GRCh38 reference set in ID/CNV/SV of COSMIC

### ISSUE THREAD

**Issue by shengxindaniu** [AlexandrovLab/SigProfilerAssignment#149]
For the mutation feature analysis of ID/CNV/SV, COSMIC does not have a corresponding GRCh38 reference set. How can SigProfiler Assignment be used for analysis

**Comment by mdbarnesUCSD** [comment]
Hi @shengxindaniu,

There is a set of [GRCh38 SV signatures](https://github.com/AlexandrovLab/SigProfilerAssignment/blob/main/SigProfilerAssignment/data/Reference_Signatures/GRCh38/COSMIC_v3.4_SV_GRCh38.txt); however, the ID and CNV signatures were derived from GRCh37 data so there is not really a set of GRCh38 signatures.

Please reach out to Marcos (e-mail is on the README) if you have any further questions. Thanks!

**Comment by shengxindaniu** [comment]
Hello, would using COSMIC of GRCh37 and CNV and SV mutations of GRCh38 for SigProfiler Assignment affect the results? If there is any impact, can you give some suggestions?
