### ISSUE TITLE
Max vcf file size?

### ISSUE THREAD

**Issue by oksalau** [AlexandrovLab/SigProfilerAssignment#150]
Hi, 

I am using the web tool with WGS data. I faced issues with one of our tumor samples. 
I am getting an error/
```
<html>` <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too `Large</
``` 
/

I assume, my file is too large? What is the maximum file size that can be used?

Thanks in advance!

**Comment by mdbarnesUCSD** [comment]
Hi @oksalau,

The maximum file size is 1GB. Thanks!
