### ISSUE TITLE
Interpreting signature probabilities for each mutation/variant in a VCF

### ISSUE THREAD

**Issue by lntran26** [AlexandrovLab/SigProfilerAssignment#152]
Follow up on a previous issue since I'd like to be able to categorize each mutation in a VCF sample by its assigned signature.

I took at look at the output files there but still have the same questions as above. Could you confirm that SigProfiler algorithm simply calls the SBS with the highest probability or it's more complicated? I do notice that the results here tend to skew way more toward a dominant SBS compare to the previous path: 

`6.040989045139073e-05	0.0	0.0	0.7239713074945375	0.14000906911576955	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.013243712486085144	0.0	0.0	0.0	0.03891348241870776	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.08380201859444865	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0`

but there are still variants where it can be quite close, e.g. between two signatures:

`0.0001331437736342248	0.0	0.0	0.015046617411096077	0.4462584121397326	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.04714382614493876	0.0	0.0	0.0	0.114888454105007	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.3765295464255912	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0`

or even three signatures:

`0.0004209922073199189	0.0	0.0	0.09195513113684133	0.2659303843753061	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.08492596007440775	0.0	0.0	0.0	0.23650530304941902	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.32026222915670594	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0`

_Originally posted by @lntran26 in https://github.com/AlexandrovLab/SigProfilerAssignment/issues/148#issuecomment-2480338360_

**Comment by marcos-diazg** [comment]
Dear @lntran26,

I hope you are doing well, and sorry for the delayed response. Regarding your question, SigProfilerAssignment does not assign an individual mutational signature to each individual somatic mutation. Instead, as you can see in the output matrix, SigProfilerAssignment provides a probability for each mutational signature to be causing each individual somatic mutation. We actually do not provide the one-to-one assignment per individual mutation as this is a probabilistic result.

Considering this, it's then a user's choice how to proceed further. For example, you can use a maximum likelihood approach, where you always take the signature with the highest probability, or make some filters, only allowing cases where a specific signature has a probability of causing an individual mutation above a certain threshold.

I strongly suggest you to check the methods of topography-associated studies ([Otlu _et al._ 2023 _Cell Reports_](https://doi.org/10.1016/j.celrep.2023.112930) and [Morganella _et al._ 2016 _Nature Communications_](https://doi.org/10.1038/ncomms11383)), which have used these approaches in the past, and reach out by email in case you have further questions.

I hope this helps, and thanks so much for your interest in our tools!
