### ISSUE TITLE
question about subtype

### ISSUE THREAD

**Issue by shenhaizhongdechanrao** [AlexandrovLab/SigProfilerAssignment#153]
Hi. I find some question about the count of mutation in SBS6.: Ref CG to C will be counted to C>G in SBS96 and also be counted in ID.
Is this normal? I think it should be only counted in ID.

**Comment by shenhaizhongdechanrao** [comment]
I use matrices = matGen.SigProfilerMatrixGeneratorFunc('china', 'GRCh37', './vcf',exome=False) to get SBS96 matrix files. I find  CG to C was counted in both files.

**Comment by mdbarnesUCSD** [comment]
It would be a great help if you could please provide more context. Could you please share:

1. What version of SigProfilerMatrixGenerator you have installed
2. An example input file that reproduces the error you are encountering
3. More information about the files that you are looking at

Thanks!

**Comment by mdbarnesUCSD** [comment]
I created a pseudo VCF file with a single indel using SigProfilerMatrixGenerator v1.2.31 and there was one INDEL and zero SBS mutations. I will be closing this issue, please re-open if you encounter otherwise.

**Comment by shenhaizhongdechanrao** [comment]
I am sorry to for the late reply. You can try this vcf file used hg38. There are 7 SBS and other subtypes, but 9 SBS in Assignment_Solution_Activities.txt
#CHROM	POS	FILTER	REF	ALT
chr14	69571531	PASS	C	A
chr2	29064898	PASS	C	A
chr1	34905089	PASS	AG	A
chr16	46672392	PASS	G	A
chr19	29527283	PASS	GG	AT
chr11	55812382	PASS	G	T
chr10	31820484	PASS	C	T
chr12	115984193	PASS	G	A
chr9	88130179	PASS	G	GT
chr20	8765256	PASS	A	T

**Comment by mdbarnesUCSD** [comment]
Hi @shenhaizhongdechanrao,

Your SBS mutations in this example are:
chr14 69571531 PASS C A
chr2 29064898 PASS C A
chr16 46672392 PASS G A
chr11 55812382 PASS G T
chr10 31820484 PASS C T
chr12 115984193 PASS G A
chr20 8765256 PASS A T

As well as this DBS (which is an additional 2 SBS, for a total of 9 SBS mutations):
chr19 29527283 PASS GG AT

These are INDELs:
chr1 34905089 PASS AG A
chr9 88130179 PASS G GT

**Comment by shenhaizhongdechanrao** [comment]
Hi, I get you. I would like to know if this is uniform and if 7 SBS can be accepted.

**Comment by mdbarnesUCSD** [comment]
If you would like to do the analysis without the DBSs being counted as SBSs, you can filter out the lines from your VCF. Do check for adjacent SBS mutations in your VCF file that will be counted as a DBS.
