### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by juberpatel** [AlexandrovLab/SigProfilerAssignment#17]
Thanks for the new tool, excited to try it out. How is it different from SigProfilerSingleSample? What is the difference between between decompose, denovo and cosmic fit? It is not very clear from the Readme. 

Is it possible to add an example of samples file? Thanks.

**Comment by rvangara** [comment]
This is an upgraded tool of SigProfilerSingleSample with better mutational signature attribution and other functionalities. 

I added some information to the Readme file regarding the three fits in the latest release v0.0.6.

The example sample file is in the SigProfilerAssignment/data/Examples/

Please reopen this if there are more questions.

Thanks
Ravi
