### ISSUE TITLE
Missing sample file to show format and order for SBS-TSB192 mutation channels

### ISSUE THREAD

**Issue by WuyangFF95** [AlexandrovLab/SigProfilerAssignment#18]
Dear @rvangara ,

I want to decompose a mutation count matrix (a.k.a. mutational spectra) with SBS TSB mutations, 192 mutational channels (4 * 6 * 4 * transcribed/untranscribed).

I cannot find the standard SBS192 or SBS384 input file in this directory. I have found a file in [`SigProfilerMatrixGenerator`](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/references/matrix/BRCA_example/BRCA_example.SBS192.all). An example mutational channel in this file is **`T:A[C>T]G`**, where the first T stands for "transcribed strand", A and G are flanking bases before and after the mutated base.

The header seems to have the same format as the format in your [wiki](https://osf.io/s93d5/wiki/5.%20Output%20-%20SBS/). Now my question is, does `SigProfilerAssignment` sensitive to the order of the mutational channels in the input file? If so, is the order in the [file](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/blob/master/SigProfilerMatrixGenerator/references/matrix/BRCA_example/BRCA_example.SBS192.all) acceptable by `SigProfilerAssignment`?

**Comment by WuyangFF95** [comment]
Dear @rvangara ,

I provided the input SBS192 matrix as the files attached: 
Mutation counts file: [ground.truth.catalog_no.hyper.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/8830348/ground.truth.catalog_no.hyper.txt)
Signature file: [ground.truth.sigs_no.hyper.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/8830350/ground.truth.sigs_no.hyper.txt)


Given the input matrix, I ran SigProfilerAssignment with the following code:
```
import os
import random
from SigProfilerAssignment import Analyzer as Analyze

# Specify and set random seed
seed_in_use = 145879
random.seed(seed_in_use)

# Specify cancer type
cancer_type = "Breast-AdenoCA"

# Make directories for results recursively
out_dir = os.getcwd()+"/SigPro/seed."+str(seed_in_use)+"/"+cancer_type+"/"
if not os.path.exists(out_dir):
  # os.mkdir() cannot make directory recursively.
  # Use os.makedirs() instead.
  os.makedirs(out_dir, exist_ok=True)

# Assign COSMIC signatures to synthetic spectra 
in_dir = home_for_data+"/SigPro/"+cancer_type
# Do signature assignment for non-hyper-mutated cancers
sigs = in_dir+"/ground.truth.sigs_no.hyper.txt"
if os.path.exists(sigs) == True:
    samples = in_dir+"/ground.truth.catalog_no.hyper.txt"
    out_dir = home_for_run+"/SigPro/seed."+str(seed_in_use)+\
          "/"+cancer_type+"/no.hyper/"
    Analyze.cosmic_fit(samples, output=out_dir, signatures=None,
                   signature_database=sigs, genome_build="GRCh37", 
                   verbose=False)
```


and it generated the error message below:

> Traceback (most recent call last):
>   File "/home/e0240162/practice/8_mSigAct_paper/attribution_paper_code/PCAWG_genome/SBS192/code/2c_Run_SigProfilerAssignment.py", line 56, in <module>
>     Analyze.cosmic_fit(samples, output=out_dir, signatures=sigs,
>   File "/home/e0240162/opt/anaconda3/envs/SigProSS/lib/python3.10/site-packages/SigProfilerAssignment/Analyzer.py", line 11, in cosmic_fit
>     decomp.spa_analyze(samples=samples,  output=output, signatures=signatures, signature_database=signature_database,nnls_add_penalty=nnls_add_penalty, nnls_remove_penalty=nnls_remove_penalty, initial_remove_penalty=initial_remove_penalty,genome_build=genome_build,  make_decomposition_plots=make_decomposition_plots, collapse_to_SBS96=collapse_to_SBS96,connected_sigs=connected_sigs, verbose=verbose,decompose_fit_option= False,denovo_refit_option=False,cosmic_fit_option=True,devopts=devopts)
>   File "/home/e0240162/opt/anaconda3/envs/SigProSS/lib/python3.10/site-packages/SigProfilerAssignment/decomposition.py", line 261, in spa_analyze
>     processAvg = sub.getProcessAvg(genomes, genome_build, "3.2")
>   File "/home/e0240162/opt/anaconda3/envs/SigProSS/lib/python3.10/site-packages/SigProfilerAssignment/decompose_sub_routines.py", line 66, in getProcessAvg
>     sigDatabase = pd.DataFrame(signatures)
> NameError: name 'signatures' is not defined. Did you mean: 'signames'?

I was wondering whether this is because of the wrong input format. If so, can you provide an example input file for SBS192 signatures and mutation counts?

**Comment by WuyangFF95** [comment]
I have found an issue of definition of function `getProcessAvg()`, on line 66 of decompose_sub_routines.py:

```
def getProcessAvg(samples, genome_build="GRCh37", cosmic_version=3.2,signature_database=None):
    paths = spa.__path__[0]
    
    if samples.shape[0]==96:
        ...
    else: # The number of mutaional channels does not equal to 96, 288, 1536, 78, 83, 48
                sigDatabase = pd.DataFrame(**_signatures_**) # line 66
```

It seems that argument `signatures` is not defined in the scope of this function -- it does not fetch the value of argument `signatures` from the top-level wrapper function `Analyzer.cosmic_fit()`.

**Comment by rvangara** [comment]
A new version of the code is to be released tonight. It fixes this bug.
I will close this ticket after the version released.

**Comment by WuyangFF95** [comment]
Thank you @rvangara!

**Comment by rvangara** [comment]
The new version is released. The bug should be fixed, if not please reopen this ticket.

Thanks,
Ravi.
