### ISSUE TITLE
Can't reproduce results using the input from supplementary file

### ISSUE THREAD

**Issue by chaos66ren** [AlexandrovLab/SigProfilerAssignment#21]
Dear Raviteja Vangara,

I am currently using SigProfilerAssignment for signature analysis. But I found I could not reproduce the results shown in the supplementary files by Alexandrov, L.B., Kim, J., Haradhvala, N.J. et al.[1], using the COSMIC Fit mode.

The input is public available: 
https://dcc.icgc.org/api/v1/download?fn=/PCAWG/mutational_signatures/Input_Data_PCAWG7_23K_Spectra_DB/Mutation_Catalogs_--_Spectra_of_Individual_Tumours/WES_TCGA_2018_03_09.zip (File WES_TCGA.96.csv after unzipping)

The output attached is also from the supplementary files.
https://dcc.icgc.org/api/v1/download?fn=/PCAWG/mutational_signatures/Signatures_in_Samples/SP_Signatures_in_Samples/TCGA_WES_sigProfiler_SBS_signatures_in_samples.csv

The reference data is from _SigProfilerAssignment/data/Reference_Signatures/GRCh38/COSMIC_v2_SBS_GRCh38.txt_

Would it be possible for me to know how to reporduce the results? Or could you please let me know what is the difference between  SigProfilerAttribution (mentioned in the paper, currently not available through through GitHub [1]) and this software SigProfilerAssignment?

I am looking forward to hearing from you. Thanks so much!

Best wishes,
Chao

Reference
1. Alexandrov, L.B., Kim, J., Haradhvala, N.J. et al. The repertoire of mutational signatures in human cancer. Nature 578, 94–101 (2020). https://doi.org/10.1038/s41586-020-1943-3

**Comment by lalexandrov1018** [comment]
The the Nature, 2020 manuscript were based on the MATLAB version of the SigProfilerSingleSample tool. You can download and use the tool from the link below to reproduce the results.
 
https://www.mathworks.com/matlabcentral/fileexchange/38724-sigprofiler

The other issues in this ticket are being handled via email.
