### ISSUE TITLE
Negative exposure edge case

### ISSUE THREAD

**Issue by aeverall** [AlexandrovLab/SigProfilerAssignment#28]
When running SigProfilerAssignment.Analyzer.decompose_fit
<img width="2993" alt="image" src="https://user-images.githubusercontent.com/31918791/183883718-69eff71a-289e-4fd8-abe1-8a3b2c7ac28c.png">

I've traced the cause of the issue:
single_sample.fit_signatures line 147 - The max exposure is adjusted to make a total match the total of input mutations. Because of the rounding taking place, this can send the max exposure negative in rare cases particularly where the number of mutations is small (e.g. for DBS signatures).
single_sample.remove_all_single_signatures lines 458-460 - The negative exposure is missed out from initialZerosIdx and selectableIdx  such that in line 528, newExposure is len(oldExposure)-1. This generates the size miss-match in the final line. 

The combination of rounding to integer exposures in several places then correcting the max exposure for the resulting difference with input exposures is not numerically safe so this should be rewritten. I expect this has a minor effect on SBS/Indel signatures where the exposures are typically very large so correcting for rounding is a small effect but the effect on DBS can be really big.

**Comment by rvangara** [comment]
Hi @aeverall ,

I apologize for the very late reply. Thanks for your insight into this problem and the suggestion. 

I have tried to reproduce this case with a number of samples, synthetically generated scenarios, with extremely low mutation counts, high sparsity matrices, and so on, and I never was able to see a case that gives a negative exposure. Probably it is too late, we can revisit this if you have a case for us to look at.  

Thanks

**Comment by Elpalet** [comment]
@rvangara  My ID matrix is this , when I excluded this sample , everything is ok.
  ################ Sample 1 #################
on 1: ############################# Initial Composition ####################################
on 1:    ID1  ID2  ID3  ID4  ID5  ID6  ID7  ID8  ID9  ID10  ID11  ID12  ID13  ID14  ID15  ID16  ID17  ID18  ID19  ID20  ID21  ID22  ID23
      0  0.0  0.0  0.0  1.0  0.0  0.0 -1.0  0.0  0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   0.0   0.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/pipeline/Genome/conda/lib/python3.12/site-packages/SigProfilerAssignment/Analyzer.py", line 132, in cosmic_fit
    decomp.spa_analyze(
  File "/data/pipeline/Genome/conda/lib/python3.12/site-packages/SigProfilerAssignment/decomposition.py", line 1023, in spa_analyze
    sub.make_final_solution(
  File "/data/pipeline/Genome/conda/lib/python3.12/site-packages/SigProfilerAssignment/decompose_subroutines.py", line 958, in make_final_solution
    ) = ss.remove_all_single_signatures(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pipeline/Genome/conda/lib/python3.12/site-packages/SigProfilerAssignment/single_sample.py", line 686, in remove_all_single_signatures
    cos_sim(genomes, np.dot(W, H)),
                     ^^^^^^^^^^^^
ValueError: shapes (83,23) and (22,) not aligned: 23 (dim 1) != 22 (dim 0)

MutationType | T94
1:Del:C:0 | 0
1:Del:C:1 | 0
1:Del:C:2 | 0
1:Del:C:3 | 0
1:Del:C:4 | 1
1:Del:C:5 | 0
1:Del:T:0 | 0
1:Del:T:1 | 0
1:Del:T:2 | 0
1:Del:T:3 | 0
1:Del:T:4 | 0
1:Del:T:5 | 0
1:Ins:C:0 | 0
1:Ins:C:1 | 0
1:Ins:C:2 | 0
1:Ins:C:3 | 0
1:Ins:C:4 | 0
1:Ins:C:5 | 0
1:Ins:T:0 | 0
1:Ins:T:1 | 0
1:Ins:T:2 | 0
1:Ins:T:3 | 0
1:Ins:T:4 | 0
1:Ins:T:5 | 0
2:Del:R:0 | 1
2:Del:R:1 | 0
2:Del:R:2 | 0
2:Del:R:3 | 0
2:Del:R:4 | 0
2:Del:R:5 | 0
3:Del:R:0 | 0
3:Del:R:1 | 0
3:Del:R:2 | 0
3:Del:R:3 | 0
3:Del:R:4 | 0
3:Del:R:5 | 0
4:Del:R:0 | 0
4:Del:R:1 | 0
4:Del:R:2 | 0
4:Del:R:3 | 0
4:Del:R:4 | 0
4:Del:R:5 | 0
5:Del:R:0 | 0
5:Del:R:1 | 0
5:Del:R:2 | 0
5:Del:R:3 | 0
5:Del:R:4 | 0
5:Del:R:5 | 0
2:Ins:R:0 | 1
2:Ins:R:1 | 0
2:Ins:R:2 | 0
2:Ins:R:3 | 0
2:Ins:R:4 | 0
2:Ins:R:5 | 0
3:Ins:R:0 | 0
3:Ins:R:1 | 0
3:Ins:R:2 | 0
3:Ins:R:3 | 0
3:Ins:R:4 | 0
3:Ins:R:5 | 0
4:Ins:R:0 | 0
4:Ins:R:1 | 0
4:Ins:R:2 | 0
4:Ins:R:3 | 0
4:Ins:R:4 | 0
4:Ins:R:5 | 0
5:Ins:R:0 | 0
5:Ins:R:1 | 0
5:Ins:R:2 | 0
5:Ins:R:3 | 0
5:Ins:R:4 | 0
5:Ins:R:5 | 0
2:Del:M:1 | 0
3:Del:M:1 | 0
3:Del:M:2 | 0
4:Del:M:1 | 0
4:Del:M:2 | 0
4:Del:M:3 | 1
5:Del:M:1 | 0
5:Del:M:2 | 0
5:Del:M:3 | 0
5:Del:M:4 | 0
5:Del:M:5 | 0

**Comment by rvangara** [comment]
Thanks to all on the thread. All the suggestions and code improvements are incorporated in v0.2.3 of SPA. 

Please feel free to notify us if this issue persists.
