### ISSUE TITLE
Missing De_Novo_map_to_COSMIC_SBS96.csv

### ISSUE THREAD

**Issue by sudogene** [AlexandrovLab/SigProfilerAssignment#40]
This is with regards to the deprecated SigProfilerExtractor (SPE) decompose method.
Previously on SPE, there exist an output called `Decompose_Solution/De_Novo_map_to_COSMIC_SBS96.csv` where the decomposed de-novo signatures were presented in this manner:

```
De novo extracted, Global NMF Signatures, L1 Error %, L2 Error %, KL Divergence, Cosine Similarity, Correlation
Signature 96-A, Signature SBS1 (..%) & Signature SBS5 (..%) & ..., ...
```

Currently on SigProfilerAssignment (SPA) there isn't such an output. Can this be added to SPA, if not the decomposition result is not complete since we don't know the actual percentage of each COSMIC signature mapped to the de novo signature.

Thank you

**Comment by marcos-diazg** [comment]
Dear @sudogene,

SigProfilerAssignment also outputs the `De_Novo_map_to_COSMIC` file when the `decompose_fit` function is used. Please feel free to reopen the ticket and let us know if that's not the case for you. You can also reach out by email at mdiazgay@health.ucsd.edu.
