### ISSUE TITLE
Decompose_fit outputs entirely different signatures

### ISSUE THREAD

**Issue by maia-munteanu** [AlexandrovLab/SigProfilerAssignment#71]
Hi there,

I've been using the SigProfilerExtractorR tool to perform signature extraction and I'd like to view the signature decomposition results for multiple solutions (not just the suggested solution). I installed the latest version of SigProfilerAssignment with pip in a clean conda environment and run decompose_fit on the SigProfilerExtractorR signature output (SBS96_S7_Signatures.txt) alongside the original sample input .txt file. Both signature extraction and decomposition are done with GRCh38 as reference. 

The job runs well and it outputs 2 folders, the de novo solution and the decomposed. The only issue is, the signatures in the de novo solution folder match those from SigProfilerExtractor, but the ones being decomposed in the other folder look nothing alike. 
[SBS_96_plots_De_Novo.pdf](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10518063/SBS_96_plots_De_Novo.pdf)
[SBS96_Decomposition_Plots.pdf](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10518064/SBS96_Decomposition_Plots.pdf)

The exact command run is:

from SigProfilerAssignment import Analyzer as Analyze
def main():
  Analyze.decompose_fit(samples,output,signatures=signatures,genome_build="GRCh38",verbose=True)
if __name__ == '__main__':
        main()

I also checked the decomposition results from SigProfilerExtractorR (1.1.0) for the suggested solution. Whilst the decomposed version is using the right signatures, the reconstructions are very poor and seem to include mutational classes that were entirely absent in the original. 
[SBS_96_plots_SBS96_De-Novo.pdf](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10518134/SBS_96_plots_SBS96_De-Novo.pdf)
[SBS96_Decomposition_Plots.pdf](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10518136/SBS96_Decomposition_Plots.pdf)

For reference, the SigProfilerExtractor commands are:

library(reticulate)
use_python("/home/dnaro/.conda/envs/torchcuda/bin/python")
library(SigProfilerExtractorR)
sigprofilerextractor(input_type = "matrix", 
                     output = output, input_data = samples, reference_genome="GRCh38", opportunity_genome="GRCh38", 
                     minimum_signatures=1, maximum_signatures=15, nmf_replicates=100, cpu=4, gpu=F, batch_size=1)

Do you have any idea what might be causing these issues with the decomposition function?

Thanks in advance,
Maia

**Comment by marcos-diazg** [comment]
Dear @maia-munteanu,

Thanks for reaching out. Could you please try to reproduce this using the latest version of SigProfilerExtractorR? Also, it would be great if you could share the `SBS96_S7_Signatures.txt` file that you are using as input _de novo_ signatures, and the `samples.txt` file used as input mutational matrix for the `decompose_fit` function.

Thanks again for your interest. Best,

Marcos

**Comment by maia-munteanu** [comment]
Dear Marcos,

Thank you for getting back to me so quickly!
I will try to replicate the issue with new newest SigProfilerExtractorR version. In the meantime, I've attached all the files inputted into the decompose_fit function (signatures and samples). I also added the activities file, if it helps in any way.

[nmf_248_samples.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10535240/nmf_248_samples.txt)
[SBS96_S7_NMF_Activities.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10535241/SBS96_S7_NMF_Activities.txt)
[SBS96_S7_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10535242/SBS96_S7_Signatures.txt)


Thanks,
Maia

**Comment by marcos-diazg** [comment]
Dear Maia,

Thanks for sharing! As I suspected, the order of the mutational types in your samples and signatures files differs from the one used in the most recent versions of all SigProfiler tools (you can see an example [here](https://osf.io/t6j7u/wiki/5.%20Output%20-%20All%20Solutions/)). If you use the latest versions, this issue should be solved. But please, feel free to get back to us if this is not the case.

**Comment by maia-munteanu** [comment]
Dear Marcos,

Thank you for help, it seems that updating to the newest version of SigProfilerExtractorR fixed the first issue, not the signatures being decomposed are the same as the original (and you were right, the order of the mutation classes was different between versions). However, I still seem to be getting rather strange decomposition results where some signatures are added which don't make a lot of sense. 

I've attached the new files for signatures, activities and the decomposition plots.
[SBS96_Decomposition_Plots.pdf](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10555588/SBS96_Decomposition_Plots.pdf)
[SBS96_S7_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10555591/SBS96_S7_Signatures.txt)
[SBS96_S7_NMF_Activities.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10555593/SBS96_S7_NMF_Activities.txt)


Thanks,
Maia

**Comment by marcos-diazg** [comment]
Dear Maia,

It seems that you are still using the same [nmf_248_samples.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/10535240/nmf_248_samples.txt) input mutational matrix file, and that may be causing your error. You need to modify the order of the rows to be in the same format as expected by the SigProfiler tools, and rerun both SigProfilerExtractor and SigProfilerAssignment.

[This](https://github.com/AlexandrovLab/SigProfilerExtractor/blob/master/SigProfilerExtractor/data/TextInput/Samples_SBS.txt) is an example of an input mutational matrix with the rows in the required order. Please note that, for example, the first six rows are A[C>A]A, A[C>A]C, A[C>A]G, A[C>A]T, **A[C>G]A, A[C>G]C**; instead of your file, which has as first six rows A[C>A]A, A[C>A]C, A[C>A]G, A[C>A]T, **C[C>A]A, C[C>A]C**.

I hope this helps, and please let me know if you have further questions.

**Comment by maia-munteanu** [comment]
Dear Marcos,

Thanks a lot! Sorting both the samples file and the outputted signatures file alphabetically did the trick!


Maia
