### ISSUE TITLE
Problem encountered when running the code in containers

### ISSUE THREAD

**Issue by superjw** [AlexandrovLab/SigProfilerAssignment#78]
Hi there,

Just wondering if you could set this dir as somewhere else like a "temp working directory"? 

https://github.com/AlexandrovLab/SigProfilerAssignment/blob/7fef91c5e1c898ccad482e4a3a783bcef53366ec/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py#L48

The current setting works fine when you have "write permission" to the library dir. However, if you put it into a container it will unlikely to function because the library path will be "read-only" most of the times.

Thanks,

Jingwei

**Comment by mdbarnesUCSD** [comment]
Hi @superjw,

Thanks for reaching out. We will be looking to modify this behavior in a future release.

**Comment by me-nobody** [comment]
Hi,
when to use this parameter, collapse_to_SBS96=True?

**Comment by nservant** [comment]
Hi @mdbarnesUCSD, 
Any news on this topic ? It would be really great to be able to profile annotation files which are intall in another folder ... as already done with the `volume` parameter here ;
https://github.com/AlexandrovLab/SigProfilerMatrixGenerator/issues/131
Thanks

**Comment by mdbarnesUCSD** [comment]
Hi @nservant and @superjw,

The volume parameter has been added as well as support for the environmental variable "SIGPROFILERASSIGNMENT_VOLUME". The environmental variable takes precedence over the parameter and should be a directory that the user has read/write access to.

**Comment by LlaneroHiboreo** [comment]
I am having the following problem running inside a singularity container:

If I run like this:

`Analyze.cosmic_fit(samples="vcf_samples",
output="./output",
input_type="vcf",
context_type="96",
exome=True,
genome_build="GRCh38",
cosmic_version=3.3,
signature_database=None,
exclude_signature_subgroups=None,
export_probabilities=False,
export_probabilities_per_mutation=False,
make_plots=True,
sample_reconstruction_plots="both",
verbose=True)`

I get the following:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/Analyzer.py", line 132, in cosmic_fit
    decomp.spa_analyze(
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/decomposition.py", line 1074, in spa_analyze
    generate_sample_reconstruction(
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/decomposition.py", line 122, in generate_sample_reconstruction
    result = plot_decomp.run_PlotSSDecomposition(
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 1070, in run_PlotSSDecomposition
    basis_plots_dict = install_cosmic_plots(
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py", line 90, in install_cosmic_plots
    os.mkdir(cosmic_template_path)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/DecompositionPlots/CosmicTemplates'
`


If I use volume parameter:

`Analyze.cosmic_fit(samples="vcf_samples",
output="./E000011_vs_E000010_output",
input_type="vcf",
context_type="96",
exome=True,
genome_build="GRCh38",
cosmic_version=3.3,
signature_database=None,
exclude_signature_subgroups=None,
export_probabilities=False,
export_probabilities_per_mutation=False,
make_plots=True,
sample_reconstruction_plots="both",
verbose=True,
volume="/some/path/")`

I get the following:
`File   | Status   | Expected MD5                     | Actual MD5                      
---------------------------------------------------------------------------------------
1.txt  | Missing  | ebe083105e7703a49581a36d73732a96 | N/A                             
2.txt  | Missing  | cd65e36dbdf12a8ac3d2c70ebac8cad4 | N/A                             
3.txt  | Missing  | 6c20a7008394f2fa9c304d231a1f391b | N/A                             
4.txt  | Missing  | 5c7443e1678868adadeac0e57558f6e8 | N/A                             
5.txt  | Missing  | 45573232c8097c679503a6598f61e60b | N/A                             
6.txt  | Missing  | cfc137c7434d3a9a872332d405b5c553 | N/A                             
7.txt  | Missing  | 9d8210c22c1962db837e7b62a578975c | N/A                             
8.txt  | Missing  | 665134fd44f21915cbeef955addf89ba | N/A                             
9.txt  | Missing  | 758d0c0c71d8bafbe1ede86587191730 | N/A                             
10.txt | Missing  | 397bb21acff1ca3052ac802f2aee06e0 | N/A                             
11.txt | Missing  | 07707ff8a2a964656469a7be7bb3e576 | N/A                             
12.txt | Missing  | 506d02539075e080ee12ebdf63908080 | N/A                             
13.txt | Missing  | 03ed22f01ab43145733c0b6a647e0560 | N/A                             
14.txt | Missing  | 8b93447086549e476c65699ed813a567 | N/A                             
15.txt | Missing  | cd0dfe9fa78cae2fc7becf8f8ec6c693 | N/A                             
16.txt | Missing  | e17bbb66eb4d6b62b7b0e2fbf062b6a6 | N/A                             
17.txt | Missing  | 8fc95bb3101d024d890aa3543eb454c5 | N/A                             
18.txt | Missing  | a4870628045bb033a90e8c89f818e24d | N/A                             
19.txt | Missing  | 6a9d0c8298f0ba2fa13180e02b969f16 | N/A                             
20.txt | Missing  | aa75d35969cf3956bb4ace7bdc57b34e | N/A                             
21.txt | Missing  | 5d55f5ad6271d6a0d8806876924990f7 | N/A                             
22.txt | Missing  | efdb4e1d23ab7964302b828062a33447 | N/A                             
Y.txt  | Missing  | 3b38c639ad164d60f1a055b46fcd2748 | N/A                             
X.txt  | Missing  | d5edbea3cf5d1716765dd4a7b41b7656 | N/A                             
MT.txt | Missing  | dfd6db5743d399516d5c8dadee5bee78 | N/A                             
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/Analyzer.py", line 132, in cosmic_fit
    decomp.spa_analyze(
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerAssignment/decomposition.py", line 308, in spa_analyze
    data = datadump.SigProfilerMatrixGeneratorFunc(
  File "/usr/local/lib/python3.10/dist-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 109, in SigProfilerMatrixGeneratorFunc
    raise Exception(
Exception: The specified genome GRCh38 has not been installed
`

How can I make it work? Any advice?
