### ISSUE TITLE
SBS96 signature assignment reproducibility using SigProfilerAssignment?

### ISSUE THREAD

**Issue by toddajohnson** [AlexandrovLab/SigProfilerAssignment#81]
I ran SigProfilerAssignment  for 396 HCC samples across a mutational matrix constructed using SigProfilerMatrixGenerator from PCAWG vcfs (lifted over to GRCh38) or vcfs from our own in house mutation calling pipeline (called using GRCh38 as ref.).  Twenty-six of the samples were called in both pipelines (our lab submitted the LIRI-JP PCAWG data).  Of some concern, the signature profiles sometimes show very large mis-matches for the assigned SBS signatures, so I don't know what values I can "trust".  I could understand that would happen if the two pipelines were outputting very different calls for the same sample, but this occurs even when the values in the mutational matrix for a sample's duplicates appear to be almost identical (r=0.9986 for the two columns) and the SigProfilerMatrixGenerator output/plots/SBS_96_plots...pdf appear identical to me for those samples.

I have attached the JOB_METADATA_SPA file and an Excel file for one sample (RK001_T) with the mutational matrix data and SBS96 signatures that were called in either of the two samples.
As one can see looking at the SBS96 signature summary table, SBS5 was assigned in both samples, but SBS8, SBS46, and SBS92 were assigned only in LIRI-JP_RK001_T and SBS12 and SBS40 were assigned only to the data from my current somatic calling pipeline.  I did not see such differences for ID or DBS in this sample.

[JOB_METADATA_SPA.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/11035690/JOB_METADATA_SPA.txt)

[RK001_T_matrix_and_COSMIC_sigs.xlsx](https://github.com/AlexandrovLab/SigProfilerAssignment/files/11035692/RK001_T_matrix_and_COSMIC_sigs.xlsx)

**Comment by marcos-diazg** [comment]
Dear @toddajohnson,

Please accept my apologies for not getting back to you sooner. Unfortunately, what you described is one of the biggest challenges that we currently face in the field of signature assignment. Considering the large pool of SBS reference signatures available, the possibility of different signature reconstructions having very similar reconstruction similarity is relatively high. Indeed, as you pointed out, almost no difference was observed for ID and DBS, with both having a much smaller number of COSMIC reference signatures.

However, there are several strategies to try to overcome this uncertainty. First, one can focus on those signatures previously related to the cancer type of interest, liver cancer in your particular case. Although this would restrict the analysis to previous knowledge, it would avoid unreliable assignment of signatures, such as SBS46 in your specific case, which is a signature related to a sequencing artifact observed in early releases of TCGA. You can exclude certain reference signatures from the assignment by using the `exclude_signature_subgroups` parameter (following the instructions on the [README](https://github.com/AlexandrovLab/SigProfilerAssignment#subgroups)) or directly providing a modified signature database using the `signature_database` parameter. Other options can include checking the transcriptional strand bias of your samples compared to the one observed in the reference signatures (available in the `topographical features` section of the [COSMIC Mutational Signatures website](https://cancer.sanger.ac.uk/signatures/)) or excluding certain etiologies based on additional information about the input samples (e.g., restricting the assignment of chemotherapy-related signatures in treatment-naive cases).

I hope this helps, and please feel free to reopen the ticket or reach out by email (mdiazgay@health.ucsd.edu) if you have further comments or questions. Thanks for your interest!
