### ISSUE TITLE
Difference between CNV signature from SigProfilerAssignment and SigprofilerExtractor

### ISSUE THREAD

**Issue by TgenJZhang** [AlexandrovLab/SigProfilerAssignment#84]
Hello! I used a sequenza segment file containing 60 samples and ran it through both SigProfilerAssigment and SigProfilerExtractor. They gave me very different results. SigProfilerAssigment's result had samples matching all 24 Cosmic CN signatures, but according to the decomposed results from Sigprofiler extractor there are only 8 cosmic CN signatures 2 de novo signatures. Why did the two packges gave such different results?  Thank you so much for your time!

**Comment by mdbarnesUCSD** [comment]
Hi @TgenJZhang,

SigProfilerExtractor and SigProfilerAssignment are doing different things. SigProfilerExtractor decomposes de novo signatures into cosmic signatures, and both de novo and cosmic signatures are used for assignment. This is different from SigProfilerAssignment's cosmic_fit, which assigns cosmic signatures to the samples.

**Comment by TgenJZhang** [comment]
I see. Thank you for the reply!
