### ISSUE TITLE
Error after updating: cosmic_fit() got an unexpected keyword argument 'input_type'

### ISSUE THREAD

**Issue by cyrusmallon** [AlexandrovLab/SigProfilerAssignment#85]
Hello, 

First of all, thank you for such a nice set of tools to work with signatures. Previously I was writing analyses for things like replication timing and processivity from scratch, but your suite of tools makes everything so much easier!

For the moment, I've run into to issues that I believe are related to library incompatibilities. 

Previously I was using these python and package versions:

```
-------Python and Package Versions------- 
Python Version: 3.9.16
SigProfilerPlotting Version: 1.3.13
SigProfilerMatrixGenerator Version: 1.2.16
SigProfilerAssignment Version: 0.0.30
Pandas version: 1.5.3
Numpy version: 1.24.3
```

I've now updated to: 

```
Python Version: 3.9.16
SigProfilerPlotting Version: 1.3.13
SigProfilerMatrixGenerator Version: 1.2.17 #changed from v1.2.16
SigProfilerAssignment Version: 0.0.6 #changed from v0.0.30
Pandas version: 1.5.3
Numpy version: 1.24.3
```
This is the code I'm trying to run, which contains an amended signature database:

```
from SigProfilerAssignment import Analyzer as Analyze

Analyze.decompose_fit(samples='/home/cyrus/replication_analysis/topology/new_signature/SBS96/Samples.txt',
                      output='/home/cyrus/replication_analysis/topology/new_signature/Decompose_fit_results',
                      input_type="matrix",
                      signatures='/home/cyrus/replication_analysis/topology/new_signature/SBS96/Suggested_Solution/SBS96_De-Novo_Solution/Signatures/SBS96_De-Novo_Signatures.txt',
                      signature_database='/home/cyrus/replication_analysis/topology/new_signature/COSMIC_v5_mm10.csv',
                      verbose=True,
                      genome_build="mm10")
```

And I get this error:

```
Traceback (most recent call last):
  File "/home/cyrus/anaconda3/envs/topology/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-2fac79574941>", line 3, in <module>
    Analyze.decompose_fit(samples='/home/cyrus/replication_analysis/topology/new_signature/SBS96/Samples.txt',
TypeError: decompose_fit() got an unexpected keyword argument 'input_type'
```
If one would like to try to reproduce, here are all the files I used:
 samples:  [Samples.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/11815907/Samples.txt)
signatures: [SBS96_De-Novo_Signatures.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/files/11815918/SBS96_De-Novo_Signatures.txt)
new signature: [COSMIC_v5_mm10.csv](https://github.com/AlexandrovLab/SigProfilerAssignment/files/11815924/COSMIC_v5_mm10.csv).

Everything was working before I updated the libraries. I had updated the libraries because `decompose_fit()` wasn't decomposing the *de novo* signatures into known cosmic signatures (the .pdf was created but it was void of any plots), and I read somewhere in issues that updating SigProfilerAssignment to v0.0.6 would solve this problem. However, there now seems to be some incompatibilities with between the versions I have. 

Any ideas as to what versions may alleviate the `keyword argument 'input_type'` error? Or any other ideas as to how to fix this?

Best wishes!

PS Here is some system info, if needed:
```
-------System Info-------
Operating System Name: Linux
Nodename: cyrus
Release: 5.19.0-45-generic
Version: #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20
```

**Comment by mdbarnesUCSD** [comment]
Hi @cyrusmallon,

The [decomposition plots are not currently supported for](https://github.com/AlexandrovLab/SigProfilerAssignment/blob/main/SigProfilerAssignment/decompose_subroutines.py#L390) custom signature databases. The v0.0.30 release is the most recent release, and the unexpected keyword issue that you are encountering is from the older v0.0.6 release. Hopefully this helps resolve any confusion.

**Comment by cyrusmallon** [comment]
Ah, thank you very much for your quick reply! I'll close the issue now.

**Comment by cyrusmallon** [comment]
PS. Are there any plans to implement this in the future (i.e., decomposition plots for signatures to an amended signature database? If there are not, perhaps I could take it up. It could make for a nice, fun project.
