### ISSUE TITLE
Difference between the pan-cancer cnv signatures provided by the paper and those provided in the github data

### ISSUE THREAD

**Issue by DingTin** [AlexandrovLab/SigProfilerAssignment#86]
Hello! Sorry for interruption but I got a problem when using SigProfilerAssignment. The aim to use SigProfilerAssignment is to define the CNV signatures of 100 different samples according to the impressing article (https://www.nature.com/articles/s41586-022-04738-6#Sec11). But I got 3 questions when I was using SigProfilerAssignment and SigProfilerExtractor.
1. What the differences between the pancancer signatures provided in the supplementary table 2 which contains 24 CN signatures and the one provided in the github data which contains 19 signatures? As the CN signature I concerned is different in the two files.
2. I have known that SigProfilerExtractor is used to de novo generate CN signatures and  SigProfilerAssignment is mainly used for refitting to the known signatures such as those mentioned in question 1. I'm wondering if it is possible for me to use SigProfilerExtractor first to generate de novo signatures, then compare them with the known ones. Does there exist a possible way to achieve the comparison? 
3. As I cheked the 24 CN signatures, I noticed on cosmic CN signatures download page it's said those signatures were derived from GRCh37,  but the reference genome I have used was GRCh38, would it effect the results?
Thanks. Looking forward to the reply.

**Comment by mdbarnesUCSD** [comment]
Hi @DingTin,

1. I want to point you to the correct file for the [CN reference signatures](https://github.com/AlexandrovLab/SigProfilerAssignment/blob/main/SigProfilerAssignment/data/Reference_Signatures/GRCh37/COSMIC_v3.3_CN_GRCh37.txt). I figure you were looking at [this file](https://github.com/AlexandrovLab/SigProfilerAssignment/blob/main/SigProfilerAssignment/data/CNV_signatures.txt), which is a dated file that looks to no longer be used.

@marcos-diazg could you please comment on 2 & 3?

Thanks!

**Comment by marcos-diazg** [comment]
Hi @DingTin and thanks @mdbarnesUCSD,

2. Indeed, SigProfilerExtractor will automatically do the comparison with the known COSMIC CN signatures for you.
3. As mentioned at https://cancer.sanger.ac.uk/signatures/downloads/, no renormalization is available for CN signatures so you can use the reference COSMIC CN signatures independently of your reference genome.

Thanks for your interest, and please feel free to reopen the ticket if you have any additional questions.
