### ISSUE TITLE
issue running sigprofilerassignment in GEL container

### ISSUE THREAD

**Issue by me-nobody** [AlexandrovLab/SigProfilerAssignment#87]
Hello,
I am using SigProfilerAssignment in the Genomics England Research Environment. I have to use it via a singularity container and this container cannot be written into; I can only use/execute it. 
I have to bind this container to my working directory, and it will write to my working directory only.
while executing it, I have run into this error, which i have listed below concisely (I HAVE ATTACHED THE COMPLETE ERROR )

>>> Analyze.cosmic_fit samples="/demo sigprofiler/input", output="./demo_sigprofiler/ouput", input_type="vcf", context_type="96", geno
Starting matrix generation for SNVS and DINUCS... Completed! Elapsed time: 10.85 seconds.
Starting matrix generation for INDELS...Completed! Elapsed time: 5.64 seconds.
Matrices generated for 4 samples with 0 errors. Total of 77021 SNVS, 767 DINUCS, and 6203 INDELS were successfully analyzed.
Assigning COSMIC sigs or Signature Database ......
4/4 [100%] in 1.9s (2.73/s)
There may be an issue with the formatting of your matrix file.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/sigProfilerPlotting/sigProfilerPlotting.py", line 1027, in plotSBS
File "/usr/local/lib/python3.9/dist-packages/sigProfilerPlotting/sigProfilerPlotting .py", line 129, in make pickle_file
os.mkdir (volume)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.9/dist-packages/sigProfilerPlotting/templates/'
.......
........
FileNotFoundError: [Errno 2] No such file or directory: './demo_sigprofiler/ouput/Assignment Solution/Signatures/SBS_96_plots_Assignment_Solution.pdf'
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

So, as I understand, during the running of the script sigprofiler plotting tries to create template files in the installed directory,  and fails to do so as the container cannot be written into and subsequently the script throws an error
I am stuck for the past 1 month and I have not been able to figure out a solution. I have requested Genomics England (GEL)  and they are able to provide this only as a container and also am I not allowed to separately install siprofiler suite and the genome in my own environment. Genomics England has some conda environment too having sigprofiler suite components partly installed, so I can't use those too. I cannot take the data out of GEL.

please, can you suggest some workaround for this. [https://drive.google.com/file/d/1cti-4q3JQS2jEU3WHE6ChsLLf1ElgziP/view?usp=sharing](url) (complete error)

Best Wishes,
Anubrata

**Comment by mdbarnesUCSD** [comment]
Hi Anubrata,

SigProfilerAssignment imports both SigProfilerPlotting and SigProfilerMatrixGenerator, which are being updated to have a user defined location for saving and loading required files from. Once those updates have been completed and adopted into this repository, we will close #78.
