### ISSUE TITLE
Some problems with CNsig

### ISSUE THREAD

**Issue by SuqinYang** [AlexandrovLab/SigProfilerAssignment#90]
Dear Team,
  Sorry to trouble you.I have a few questions to ask.
  I got the segments files from "SEQUENZA", Below is an example:
sample chromosome start.pos end.pos Bf N.BAF sd.BAF depth.ratio N.ratio sd.ratio CNt A B LPP
GYZ131 chr1 2652268 124764019 0.040122140324882 68 0.125082718021609 0.752397218399748 1479 1.63243750373485 8 8 0 -6.77754515442662
GYZ131 chr1 125079855 125165717 0.113879024005992 58 0.153735168772023 0.201522866987084 164 0.405503622043809 2 2 0 -6.73509300742253

I got the "matrix.tsv" file by using the "cosmic_fit" from "SigProfilerAssignment":
MutationType    GYZ131 GYZ132      
0:homdel:0-100kb        12      0      
0:homdel:100kb-1Mb      1       0     
0:homdel:>1Mb   2       1       
 and I got a similar"matrix.tsv" file by using the "generateCNVMatrix" from "SigProfilerMatrixGenerator.scripts".What's the difference between these two？

I don't know how to get the CNsig(CN1-CN21) with "matrix.tsv" just like the table below.Besides,I'm confused about the "Median attributions" and "Proportion attributed".Thank you so much!
CNsig	ACC	BLCA	BRCA
CN1	0.191011236	0.346774194	0.46372549
CN2	0.460674157	0.521505376	0.461764706
CN3	0.02247191	0	0
CN4	0.02247191	0	0
CN24	0.02247191	0.032258065	0.039215686
CN6	0.191011236	0.182795699	0.194117647
CN7	0.011235955	0.016129032	0.304901961
CN8	0.06741573	0.241935484	0.061764706
CN9	0.146067416	0.282258065	0.340196078
.....
CN21	0.04494382	0	0.002941176

**Comment by marcos-diazg** [comment]
Dear @SuqinYang,

Thanks for your interest in our tool! SigProfilerAssignment is indeed using SigProfilerMatrixGenerator internally to generate the mutational matrix, so it is expected that you get the same matrix using both tools. There should not be any difference between the two matrices.

However, SigProfilerAssignment aims to assign mutational signatures to your input sample/s and obtain your signature activities (also known as attributions). To do this, please follow the instructions in the [README](https://github.com/AlexandrovLab/SigProfilerAssignment), and you will have your results in the output folder defined in the `output` parameter. If you have any questions about the output folder structure, please have a look at our [wiki page](https://osf.io/mz79v/wiki/home/).

I hope this helps, and thanks again!

**Comment by SuqinYang** [comment]
Dear @marcos-diazg,
 Thank you for your reply. It helps me a lot!
