### ISSUE TITLE
Difference in Activities from SigProfilerExtractor and SigProfilerAssignment

### ISSUE THREAD

**Issue by micoli98** [AlexandrovLab/SigProfilerAssignment#93]
Hi, 
I used SigProfilerExtractor v1.1.21 for de novo exctraction of CN signatures and sigProfilerAssignment v0.0.30 on the same samples used for the extraction. I compared the activities assigned to the samples in the De_Novo_Solution from the extraction and the Activities in the denovo_fit results from SigProfilerAssignment (no decomposition into COSMIC because I'm using other features). The activities are completely different even if I'm using the same penalties in both tools. How is it possible? What should I change to match them?

**Comment by mdbarnesUCSD** [comment]
Hi @micoli98,

Thanks for reaching out. Could you please provide your output directories so that we can take a closer look? You can send via e-mail mdbarnes@ucsd.edu.

Thanks!

**Comment by micoli98** [comment]
Thank you, I just sent them to that email

**Comment by mdbarnesUCSD** [comment]
Hi @micoli98,

I reviewed your output files from SigProfilerExtractor and SigProfilerAssignment and then reproduced the environment with package versions listed in your JOB_METADATA.txt file. Samples.txt and De_Novo_Signatures.txt were used for input and SigProfilerAssignment's denovo_fit() was ran. The output activity matrix was the same as the activity matrix from SigProfilerExtractor. I suspect the input file for SigProfilerAssignment and SigProfilerExtractor may have been different during your run. Please reach out if you have any additional questions.

Thanks!
