### ISSUE TITLE
Sample reconstruction plotting fails when using matrix input 

### ISSUE THREAD

**Issue by alvinwt** [AlexandrovLab/SigProfilerAssignment#94]
Hi, I am trying to plot the sample reconstruction plots using a matrix input and there is the below error. I used the example matrix from the test data [sample_matrix_SBS.txt](https://github.com/AlexandrovLab/SigProfilerAssignment/blob/7a2420e939188f46376af74c2dc8c3949228b727/SigProfilerAssignment/data/tests/txt_input/sample_matrix_SBS.txt) in the repo and produced the error. Could you kindly check if sample reconstruction plotting works for this version of the code? 

```
File ~/miniconda3/envs/sigProfilerEnv/lib/python3.8/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py:596, in run_PlotSSDecomposition(denovo_mtx, denovo_name, basis_mtx, basis_names, weights, output_path, project, context_type, genome_build, cosmic_version, custom_text, exome)
    591 reconstructed_mtx,reconstruction_plot_dict = gen_reconstructed_png_numerical(
    592         denovo_mtx, denovo_name, basis_mtx,
    593         basis_names, weights, output_path, project, context_type)
    595 print(denovo_plots_dict)
--> 596 denovo_plots_dict = convert_to_imgReaderDict(denovo_plots_dict)
    597 # subset basis_plots_dict to only the plots used
    598 basis_plots_dict = {key: basis_plots_dict[key] for key in basis_names}

File ~/miniconda3/envs/sigProfilerEnv/lib/python3.8/site-packages/SigProfilerAssignment/DecompositionPlots/PlotDecomposition.py:162, in convert_to_imgReaderDict(image_dict)
    160 def convert_to_imgReaderDict(image_dict):
    161         imgReader_dict = dict()
--> 162         for name in image_dict.keys():
    163                 imgReader_dict[name] = ImageReader(image_dict[name])
    164         return imgReader_dict

AttributeError: 'NoneType' object has no attribute 'keys'


## command run 
 Analyze.cosmic_fit('recon_test/input/sample_matrix_SBS.txt', 
'recon_test', 
input_type="matrix",
genome_build="GRCh37",
make_plots=True,
sample_reconstruction_plots='png', verbose=True)

```

**Comment by marcos-diazg** [comment]
Dear @alvinwt,

I hope you are doing well, and thanks for your question. Could you please make sure that you are using the most recent versions of SigProfilerAssignment (v0.0.31), SigProfilerPlotting (v1.3.15), and SigProfilerMatrixGenerator (v1.2.17)? I have tested your code using the same input matrix, and no errors on my end.

**Comment by alvinwt** [comment]
Thanks for the quick reply Marcos,

I checked the versions and they are correct. I created a new conda
environment with the packages and it is working fine now. There might be
conflicts since I have used the environment for a long time. Happy to close
the issue now. thanks again!

**Comment by marcos-diazg** [comment]
Great! I'm glad the issue is solved. I also suspect a conflict with some of the dependencies may be the cause. Thanks again for your interest, and please feel free to reach out if you have any other questions.
