### ISSUE TITLE
Unable to decompose signatures into COSMIC for SBS192 or SBS384

### ISSUE THREAD

**Issue by skeitaa** [AlexandrovLab/SigProfilerAssignment#99]
Hello,

I've been trying to decompose de novo signatures I extracted from a sample set into COSMIC signatures. SigProfilerAssignment seems to work fine for SBS96 and SBS288 but I get a very different output for SBS192 and SBS384 (which are the most interesting to my goals on this project): the decomposition plots are not plotted and I get this type of "Custom Signature" plot: 
![custom_sig_plot](https://github.com/AlexandrovLab/SigProfilerAssignment/assets/97189680/28d35f1d-4ff3-4871-bcdc-d62eddafb839)

I would like to get the regular SigProfilerPlotting plots and the decomposition into COSMIC plots as an output. Is that possible ? I noticed that it wasn't done in the recent re-analysis of PCAWG data that led to new discussions about SBS92, so maybe it is just not possible at the moment?

Thanks for your help and best regards,
Stephane

**Comment by mdbarnesUCSD** [comment]
Hi Stephane,

There are no supported decomposition plots for SBS192 or SBS384 currently. Please update SigProfilerAssignment to v0.0.33, which now has SBS384 de novo signature plots generated using SigProfilerPlotting.

Please reach out again if you have any questions, thanks!

**Comment by skeitaa** [comment]
Hi,

Thanks for the answer and the info about the latest update!
